services:
  - type: web
    plan: free
    name: thai_massage
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn thai_massage.asgi:application -k uvicorn.workers.UvicornWorker'