# Generated by Django 5.1.5 on 2025-01-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Treatments',
        ),
    ]
