# Generated by Django 5.1.5 on 2025-01-31 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatments',
            name='one_hour',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='two_hour',
            field=models.DecimalField(decimal_places=2, default=110.0, max_digits=6),
        ),
    ]
