# Generated by Django 5.1.5 on 2025-01-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_service_treatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatments',
            name='half_hour',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='one_hour',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='two_hour',
            field=models.DecimalField(decimal_places=2, default=55.0, max_digits=6),
        ),
    ]
